# Generated by Django 3.1.6 on 2021-02-15 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epolishstation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.EmailField(max_length=30)),
                ('feedback', models.CharField(max_length=60)),
            ],
        ),
    ]
