# Generated by Django 3.1.6 on 2021-02-16 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epolishstation', '0002_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='feedback',
            new_name='cmnt',
        ),
    ]
