# Generated by Django 3.1.5 on 2021-02-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epolishstation', '0004_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('uname', models.EmailField(max_length=50)),
                ('msg', models.CharField(max_length=800)),
            ],
        ),
    ]
