# Generated by Django 3.1.5 on 2021-02-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epolishstation', '0005_contactmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='emergencynumbermodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(max_length=20)),
                ('info', models.CharField(max_length=50)),
            ],
        ),
    ]
