# Generated by Django 3.1.5 on 2021-02-22 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epolishstation', '0008_casestatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='casestatus',
        ),
    ]
