# Generated by Django 3.1.5 on 2021-02-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epolishstation', '0009_delete_casestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='casestatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.EmailField(max_length=30)),
                ('complains', models.CharField(max_length=900)),
                ('aadhar', models.FileField(upload_to='upload')),
                ('status', models.CharField(max_length=20)),
            ],
        ),
    ]
