# Generated by Django 3.1.7 on 2021-02-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epolishstation', '0010_casestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='commisnermodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_uname', models.EmailField(max_length=70)),
                ('c_password', models.CharField(max_length=50)),
            ],
        ),
    ]
