# Generated by Django 3.1.7 on 2021-03-08 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epolishstation', '0011_commisnermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='aadhar',
            field=models.ImageField(upload_to='media'),
        ),
    ]
