# Generated by Django 3.1.7 on 2021-03-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epolishstation', '0013_auto_20210308_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='aadhar',
            field=models.ImageField(upload_to='imagee'),
        ),
    ]
